
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class AboutPage extends javax.swing.JFrame {

    /**
     * Creates new form AboutPage
     */
    public AboutPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sajid = new javax.swing.JButton();
        Biggo = new javax.swing.JButton();
        Iftekhar = new javax.swing.JButton();
        Shafkat = new javax.swing.JButton();
        Atik = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sajid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/About/Sajid.png"))); // NOI18N
        Sajid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sajid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SajidActionPerformed(evt);
            }
        });
        getContentPane().add(Sajid, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 100, 20));

        Biggo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/About/Biggo.png"))); // NOI18N
        Biggo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Biggo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiggoActionPerformed(evt);
            }
        });
        getContentPane().add(Biggo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 100, 20));

        Iftekhar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/About/Iftekhar.png"))); // NOI18N
        Iftekhar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Iftekhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IftekharActionPerformed(evt);
            }
        });
        getContentPane().add(Iftekhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 100, 20));

        Shafkat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/About/Shafkat.png"))); // NOI18N
        Shafkat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Shafkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShafkatActionPerformed(evt);
            }
        });
        getContentPane().add(Shafkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 100, 20));

        Atik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/About/Atik.png"))); // NOI18N
        Atik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Atik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtikActionPerformed(evt);
            }
        });
        getContentPane().add(Atik, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 100, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/About/covidTest.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/About/covidResponse.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/About/HealthyDiet.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/About/shopping.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 200, 50));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/About/LeisureTime.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 200, 50));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/About/AboutUs.png"))); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 200, 50));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/About/Home.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/About/AboutPage.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(916, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IftekharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IftekharActionPerformed
        try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://github.com/Iftekhar-Ifat"));
        } catch (IOException ex) {
            Logger.getLogger(AboutPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_IftekharActionPerformed

    private void SajidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SajidActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://github.com/tryit-100"));
        } catch (IOException ex) {
            Logger.getLogger(AboutPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SajidActionPerformed

    private void BiggoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiggoActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://github.com/Biggo111"));
        } catch (IOException ex) {
            Logger.getLogger(AboutPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BiggoActionPerformed

    private void ShafkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShafkatActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://github.com/SyedShafkatulHassan"));
        } catch (IOException ex) {
            Logger.getLogger(AboutPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ShafkatActionPerformed

    private void AtikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtikActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://github.com/akteratikofficial"));
        } catch (IOException ex) {
            Logger.getLogger(AboutPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AtikActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Frontpage frPage = new Frontpage();
        frPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CovidTestUI cvdTst = new CovidTestUI();
        cvdTst.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ShoppingFrontPage shpFrntpage = new ShoppingFrontPage();
        shpFrntpage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LeisureTime lt = new LeisureTime();
        lt.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CovidResponse cvdRes = new CovidResponse();
        cvdRes.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atik;
    private javax.swing.JButton Biggo;
    private javax.swing.JButton Iftekhar;
    private javax.swing.JButton Sajid;
    private javax.swing.JButton Shafkat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
