
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class AmbulanceService extends javax.swing.JFrame {

    /**
     * Creates new form AmbulanceService
     */
    public AmbulanceService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hos_Ambulance = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Private_Ambulance = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hos_Ambulance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Hos_Ambulance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sylhet MAG Osmani Medical College", "Dhaka Medical College", "Chittagong Medical College", " " }));
        Hos_Ambulance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hos_AmbulanceActionPerformed(evt);
            }
        });
        getContentPane().add(Hos_Ambulance, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 90, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 90, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("OK");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 80, -1));

        Private_Ambulance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Private_Ambulance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Sylhet", "Chittagong" }));
        getContentPane().add(Private_Ambulance, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 90, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("OK");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 80, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/Emergency Response/AmbulanceService.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(916, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new CovidResponse().toFront();
        new CovidResponse().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Hos_AmbulanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hos_AmbulanceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Hos_AmbulanceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(Hos_Ambulance.getSelectedItem().equals("Sylhet MAG Osmani Medical College"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.somch.gov.bd/hospital/page/en/service/94"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(Hos_Ambulance.getSelectedItem().equals("Dhaka Medical College"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.dmc.gov.bd/site/page/364806aa-624b-486f-87dc-61bcfef1296f/-"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(Hos_Ambulance.getSelectedItem().equals("Chittagong Medical College"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://cmch.gov.bd/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(Private_Ambulance.getSelectedItem().equals("Dhaka"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://hasbd.com/ambulances/ambulance-service-in-dhaka/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(Private_Ambulance.getSelectedItem().equals("Sylhet"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.doctoradress.com/sylhet-ambulance-number-list/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(Private_Ambulance.getSelectedItem().equals("Chittagong"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.doctoradress.com/chittagong-ambulance-number-list/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AmbulanceService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AmbulanceService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AmbulanceService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AmbulanceService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AmbulanceService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Hos_Ambulance;
    private javax.swing.JComboBox<String> Private_Ambulance;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
