
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class DoctorContact extends javax.swing.JFrame {

    /**
     * Creates new form DoctorContact
     */
    public DoctorContact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        dept_box = new javax.swing.JComboBox<>();
        hos_box = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 433, 110, 30));

        dept_box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dept_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiology", "General Surgery", "Neurology", "Pathology" }));
        dept_box.setMinimumSize(new java.awt.Dimension(243, 21));
        dept_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dept_boxActionPerformed(evt);
            }
        });
        getContentPane().add(dept_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 100, -1));

        hos_box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hos_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sylhet MAG Osmani Medical College", "Dhaka Medical College", "Chittagong Medical College" }));
        getContentPane().add(hos_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 100, 20));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("OK");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/Emergency Response/Doctor'sContact.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(916, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new CovidResponse().toFront();
        new CovidResponse().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(hos_box.getSelectedItem().equals("Dhaka Medical College") && dept_box.getSelectedItem().equals("Cardiology"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.whereindoctor.com/2018/08/cardiology-heart-specialist-doctor-list.html"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(hos_box.getSelectedItem().equals("Sylhet MAG Osmani Medical College") && dept_box.getSelectedItem().equals("Cardiology"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://specialistdoctorsbd.com/cardiologist-sylhet-heart-specialist/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(hos_box.getSelectedItem().equals("Chittagong Medical College") && dept_box.getSelectedItem().equals("Cardiology"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://cmccardio.org/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(hos_box.getSelectedItem().equals("Dhaka Medical College") && dept_box.getSelectedItem().equals("General Surgery"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://specialistdoctorsbd.com/general-surgery-specialist/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(hos_box.getSelectedItem().equals("Sylhet MAG Osmani Medical College") && dept_box.getSelectedItem().equals("General Surgery"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.doctorbangladesh.com/prof-dr-dewan-ali-hassan-chowdhury/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(hos_box.getSelectedItem().equals("Chittagong Medical College") && dept_box.getSelectedItem().equals("General Surgery"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.doctorbangladesh.com/prof-dr-md-anwarul-haque/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(hos_box.getSelectedItem().equals("Dhaka Medical College") && dept_box.getSelectedItem().equals("Neurology"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://doctorlistbook.com/best-neurologist-in-dhaka/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(hos_box.getSelectedItem().equals("Sylhet MAG Osmani Medical College") && dept_box.getSelectedItem().equals("Neurology"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.somch.gov.bd/hospital/department/en/297/neuro-medicine"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(hos_box.getSelectedItem().equals("Chittagong Medical College") && dept_box.getSelectedItem().equals("Neurology"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://findoutadoctor.blogspot.com/2016/08/neuromedicine-specialist-in-chittagong.html"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(hos_box.getSelectedItem().equals("Dhaka Medical College") && dept_box.getSelectedItem().equals("Pathology"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://dcimch.com/hospital/department/pathology-lab-medicine/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(hos_box.getSelectedItem().equals("Sylhet MAG Osmani Medical College") && dept_box.getSelectedItem().equals("Pathology"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.somch.gov.bd/hospital/department/en/288/pathology"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(hos_box.getSelectedItem().equals("Chittagong Medical College") && dept_box.getSelectedItem().equals("Pathology"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.bapath.org/members/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dept_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dept_boxActionPerformed
        // TODO add your handling code here:
        if(dept_box.getSelectedItem().equals("Cardiology"))
        {
            hos_box.removeAllItems();
            hos_box.setSelectedItem(null);
            hos_box.addItem("Sylhet MAG Osmani Medical College");
            hos_box.addItem("Dhaka Medical College");
            hos_box.addItem("Chittagong Medical College");
        }
        else if(dept_box.getSelectedItem().equals("General Surgery"))
        {
            hos_box.removeAllItems();
            hos_box.setSelectedItem(null);
            hos_box.addItem("Sylhet MAG Osmani Medical College");
            hos_box.addItem("Dhaka Medical College");
            hos_box.addItem("Chittagong Medical College");
        }
        else if(dept_box.getSelectedItem().equals("Neurology"))
        {
            hos_box.removeAllItems();
            hos_box.setSelectedItem(null);
            hos_box.addItem("Sylhet MAG Osmani Medical College");
            hos_box.addItem("Dhaka Medical College");
            hos_box.addItem("Chittagong Medical College");
        }
        else if(dept_box.getSelectedItem().equals("Pathology"))
        {
            hos_box.removeAllItems();
            hos_box.setSelectedItem(null);
            hos_box.addItem("Sylhet MAG Osmani Medical College");
            hos_box.addItem("Dhaka Medical College");
            hos_box.addItem("Chittagong Medical College");
        }
    }//GEN-LAST:event_dept_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dept_box;
    private javax.swing.JComboBox<String> hos_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
