/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;

public class HospitalService extends javax.swing.JFrame {

    /**
     * Creates new form HospitalService
     */
    public HospitalService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        area_box = new javax.swing.JComboBox<>();
        hospital_box = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area_box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        area_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Chittagong", "Rajshahi", "Khulna", "Barisal", "Sylhet", "Mymensingh", "Rangpur" }));
        area_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area_boxActionPerformed(evt);
            }
        });
        getContentPane().add(area_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 180, 30));

        hospital_box.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hospital_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SQUARE HOSPITAL", "DHAKA MEDICAL COLLEGE", "Bangabandhu Sheikh Mujib Medical University (BSMMU) / (PG)", "UNITED HOSPITAL LIMITED", "GREEN LIFE MEDICAL COLLEGE HOSPITAL" }));
        getContentPane().add(hospital_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 180, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 90, -1));

        back_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back_button.setText("Back");
        back_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PandemicVsWe/Images/Emergency Response/HospitalService.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(916, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void area_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area_boxActionPerformed
        // TODO add your handling code here:
        if(area_box.getSelectedItem().equals("Dhaka"))
        {
            hospital_box.removeAllItems();
            hospital_box.setSelectedItem(null);
            hospital_box.addItem("SQUARE HOSPITAL");
            hospital_box.addItem("DHAKA MEDICAL COLLEGE");
            hospital_box.addItem("Bangabandhu Sheikh Mujib Medical University (BSMMU) / (PG)");
            hospital_box.addItem("UNITED HOSPITAL LIMITED");
            hospital_box.addItem("BIRDEM GENERAL HOSPITAL");
        }
        else
        if(area_box.getSelectedItem().equals("Chittagong"))
        {
            hospital_box.removeAllItems();
            hospital_box.setSelectedItem(null);
            hospital_box.addItem("Chittagong Medical College");
            hospital_box.addItem("Chattagram International Medical College and Hospital");
            hospital_box.addItem("Jameson Red Crescent Maternity Hospital");
            hospital_box.addItem("Royal Hospital");
            hospital_box.addItem("Evercare Hospital");
        }
        else
        if(area_box.getSelectedItem().equals("Rajshahi"))
        {
            hospital_box.removeAllItems();
            hospital_box.setSelectedItem(null);
            hospital_box.addItem("Rajshahi Medical College Hospital");
            hospital_box.addItem("Rajshahi Model Hospital");
            hospital_box.addItem("Islami Bank Hospital");
            hospital_box.addItem("I.D Hospital");
            hospital_box.addItem("Rajshahi Metropolitan Hospital Ltd.");
        }
        else
        if(area_box.getSelectedItem().equals("Khulna"))
        {
            hospital_box.removeAllItems();
            hospital_box.setSelectedItem(null);
            hospital_box.addItem("Khulna City Medical College Hospital");
            hospital_box.addItem("Khulna Healthcare Hospital ( Pvt) Ltd");
            hospital_box.addItem("Khulna Medical College Hospital");
            hospital_box.addItem("Shaheed Sheikh Abu Naser Specialised Hospital");
            hospital_box.addItem("Islami Bank Hospital");
        }
        else
        if(area_box.getSelectedItem().equals("Barisal"))
        {
            hospital_box.removeAllItems();
            hospital_box.setSelectedItem(null);
            hospital_box.addItem("Ambia Memorial Hospital");
            hospital_box.addItem("BAVS Maternity Hospital");
            hospital_box.addItem("Fair Health Clinic");
            hospital_box.addItem("Islami Bank Hospital");
            hospital_box.addItem("Apollo Diagnostic Complex (Pvt) Ltd.");
        }
        else
        if(area_box.getSelectedItem().equals("Sylhet"))
        {
            hospital_box.removeAllItems();
            hospital_box.setSelectedItem(null);
            hospital_box.addItem("MAG Osmani Medical College Hospital");
            hospital_box.addItem("Jalalabad Ragib-Rabeya Medical College & Hospital");
            hospital_box.addItem("Al Haramain Hospital Pvt Ltd.");
            hospital_box.addItem("Sylhet Women’s Medical College Hospital");
            hospital_box.addItem("Mount Adora Hospital");
        }
        else
        if(area_box.getSelectedItem().equals("Mymensingh"))
        {
            hospital_box.removeAllItems();
            hospital_box.setSelectedItem(null);
            hospital_box.addItem("Mymensingh Medical College Hospital");
            hospital_box.addItem("Community Based Medical College Hospital");
            hospital_box.addItem("Mymensingh Union Specialized Hospital");
            hospital_box.addItem("Swadesh Hospital Pvt. Ltd.");
            hospital_box.addItem("Islami Bank Community Hospital Mymensingh Limited");
        }
        else
        if(area_box.getSelectedItem().equals("Rangpur"))
        {
            hospital_box.removeAllItems();
            hospital_box.setSelectedItem(null);
            hospital_box.addItem("Dinajpur Medical College Hospital");
            hospital_box.addItem("Prime Medical College Hospital");
            hospital_box.addItem("Good Health Hospital");
            hospital_box.addItem("Rangpur Community Medical College");
            hospital_box.addItem("Rangpur Medical College Hospital");
        }
    }//GEN-LAST:event_area_boxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if(hospital_box.getSelectedItem().equals("DHAKA MEDICAL COLLEGE"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.dmc.gov.bd/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("SQUARE HOSPITAL"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.squarehospital.com/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Bangabandhu Sheikh Mujib Medical University (BSMMU) / (PG)"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://bsmmu.edu.bd/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("UNITED HOSPITAL LIMITED"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.uhlbd.com"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("BIRDEM GENERAL HOSPITAL"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.birdembd.org"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Chittagong Medical College"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://cmch.gov.bd/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Chattagram International Medical College and Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.cimch.edu.bd/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Jameson Red Crescent Maternity Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://bdrcs.org/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Royal Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("//www.doctorbangladesh.com/royal-hospital-ctg-doctor-list-contact/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Evercare Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.evercarebd.com/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Rajshahi Medical College Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://rmc.gov.bd/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Rajshahi Model Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.doctorbangladesh.com/rajshahi-model-hospital-doctor-list-contact/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Islami Bank Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://specialistdoctorsbd.com/islami-bank-hospital-rajshahi/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("I.D Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://topdoctorsbd.blogspot.com/2020/10/id-hospital-hospital-in-rajshahi.html"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Rajshahi Metropolitan Hospital Ltd."))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://en.rajshahiad.com/Clinic%20and%20Hospital/Rajshahi%20Metropolitan%20Hospital%20Ltd.%20And%20Diagnostic%20Center"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Khulna City Medical College Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://khulnacitymedicalcollege.edu.bd/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Khulna Healthcare Hospital ( Pvt) Ltd"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.facebook.com/Khulna-Health-Care-Hospital-Pvt-Ltd-%E0%A6%96%E0%A7%81%E0%A6%B2%E0%A6%A8%E0%A6%BE-%E0%A6%B9%E0%A7%87%E0%A6%B2%E0%A7%8D-%E0%A6%A5-%E0%A6%95%E0%A7%87%E0%A7%9F%E0%A6%BE%E0%A6%B0-%E0%A6%B9%E0%A6%BE%E0%A6%B8%E0%A6%AA%E0%A6%BE%E0%A6%A4%E0%A6%BE%E0%A6%B2-1593189867358086/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Khulna Medical College Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.khulnamedicalcollege.org/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Shaheed Sheikh Abu Naser Specialised Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://facilityregistry.dghs.gov.bd/org_profile.php?org_code=10001811"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Islami Bank Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://findoutadoctor.blogspot.com/2021/01/islami-bank-hospital-khulna.html"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Ambia Memorial Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://ambiamemorialhospital.songzog.com/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("BAVS Maternity Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://reviewbangla.com/bn/business/bavs-maternity-hospital-barisal/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Fair Health Clinic"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://vymaps.com/BD/Fair-Health-Clinic-17984/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Islami Bank Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.ibfbd.org/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Apollo Diagnostic Complex (Pvt) Ltd."))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://south-apollo-diagnostic-complex-pvt-ltd.business.site/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("MAG Osmani Medical College Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.somch.gov.bd/hospital/index/bn/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Jalalabad Ragib-Rabeya Medical College & Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.jrrmc.edu.bd/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Al Haramain Hospital Pvt Ltd."))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.haramainhospital.com/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Sylhet Women’s Medical College Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.swmc.edu.bd/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Mount Adora Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://mountadora.com/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Mymensingh Medical College Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.mmc.gov.bd/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Community Based Medical College Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.cbmcb.org/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Mymensingh Union Specialized Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.doctorbangladesh.com/union-hospital-mymensingh-doctor-list-contact/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Swadesh Hospital Pvt. Ltd."))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.facebook.com/pages/Swadesh-Hospital-Pvtltd/180185605504491?nr"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Islami Bank Community Hospital Mymensingh Limited"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://www.ibh.org/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Dinajpur Medical College Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.marmcd.edu.bd/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Prime Medical College Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://pmc-bd.org/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Good Health Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("https://ghhrangpur.business.site/?utm_source=gmb&utm_medium=referral"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Rangpur Community Medical College"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://www.rcmc.com.bd/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(hospital_box.getSelectedItem().equals("Rangpur Medical College Hospital"))
       {
           try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(URI.create("http://mch.rangpur.gov.bd/"));
        } catch (IOException ex) {
            Logger.getLogger(HospitalService.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new CovidResponse().toFront();
        new CovidResponse().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> area_box;
    private javax.swing.JButton back_button;
    private javax.swing.JComboBox<String> hospital_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
